[workspace]
authors = ["Mark Servilla <mark.servilla@gmail.com>"]
channels = ["conda-forge"]
description = "Pushing data packages from block storage to AWS S3 object storage"
name = "s3push"
platforms = ["linux-64", "linux-aarch64"]
version = "0.0.1"

[tasks]
install = "pip install ."
clean = "rm -rf .pixi"

[dependencies]
boto3 = ">=1.42.53,<2"
click = ">=8.3.1,<9"
daiquiri = ">=3.0.0,<4"
sqlalchemy = ">=2.0.46,<3"
pixi-pycharm = ">=0.0.10,<0.0.11"
ruff = ">=0.15.2,<0.16"
pytest = ">=9.0.2,<10"
psycopg2 = ">=2.9.11,<3"
pip = ">=26.0.1,<27"
setuptools = ">=82.0.0,<83"
botocore = ">=1.42.53,<2"
